name: Node.js CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: ESLint Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
 
    - name: Install dependencies
      run: npm install --dev
      
    - name: Run test
      run: eslint .
      
    env:
      CI: true